[project]
name = "fast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.2",
    "portion>=2.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
